language: php
php:
  - 5.5

mysql:
  database: druplex
  username: root
  encoding: utf8

before_script:
 - mysql -e 'drop database if exists druplex;'
 - mysql -e 'create database druplex;'
 - composer selfupdate
 - composer global require drush/drush:^7
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - drush make drushmake/fixture.make drupal
 - cp -r drushmake/fixture drupal/profiles
 - cp -r drushmake/druplex_feature drupal/sites/all/modules
 - cd drupal
 - env PHP_OPTIONS="-d sendmail_path=`which true`" drush site-install fixture --yes --db-url=mysql://root:@localhost/druplex
 - cd ..
 - composer --no-progress install

script:
  - vendor/bin/phpunit
